Windows: Fix build issue with newer Visual Studio
Encountered this error after updates to Visual Studio.

5>rarpch.cpp

5>c:\program files (x86)\windows kits\10\include\10.0.22621.0\um\winnt.h(2535): error C2338: Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined.

It seems that libclamunrar VS project file was set to 4-byte struct
member alignment. Changing this to "Default" fixes the issue.