Fix build issue in oss-fuzz environment
There is an error building clam with the rust nightly compiler:

error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /rust/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

We need this to work because oss-fuzz is apparently using rust nightly
in their image.

Bumping the proc-macro2 crate version in Cargo.lock resolves the error.